# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project_001' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  
  # Pods for Project_001
  
  target 'Project_001Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Project_001UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
